#!/bin/bash
arch=$(uname -m)
emsdk_version=3.1.73

if [[ "$arch" == "arm64" || "$arch" == "aarch64" ]]; then
  docker build -t lok-wasm:$emsdk_version --build-arg ARCH=-arm64 --build-arg VER=$emsdk_version .
else
  docker build -t lok-wasm:$emsdk_version --build-arg VER=$emsdk_version .
fi
mkdir -p .cache .npm

# 引数が渡されたらそれをコンテナ内で実行、なければ従来通り対話bashを起動
if [ $# -eq 0 ]; then
  set -- bash
fi

exec docker run \
  --rm \
  -it \
  -v $(pwd)/libreoffice-core:/libreoffice-core \
  -v $(pwd)/scripts:/scripts \
  -v $(pwd)/VERSION:/VERSION \
  -v $(pwd)/soffice_fccache.data:/soffice_fccache.data \
  -v $(pwd)/soffice_fccache.data.js.metadata:/soffice_fccache.data.js.metadata \
  -v $(pwd)/.cache:/.cache:rw \
  -v $(pwd)/.npm:/.npm:rw \
  -u $(id -u):$(id -g) \
  -w / \
  lok-wasm:$emsdk_version \
  "$@"
